# Production profile: keep display/audio drivers, but disable debug output.
CONFIG_GPIO=y
CONFIG_I2S=y
CONFIG_DMA=y
CONFIG_I2S_STM32_TX_BLOCK_COUNT=12
CONFIG_SPI=y
CONFIG_DISPLAY=y
CONFIG_ST7735R=y
CONFIG_MIPI_DBI=y

CONFIG_LOG=n
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n
CONFIG_SERIAL=n
CONFIG_USB_DEVICE_STACK=n
CONFIG_USB_CDC_ACM=n
