# Native Zephyr device_next USB Audio Class 2 receiver profile.
CONFIG_USB_DEVICE_STACK=n
CONFIG_USB_CDC_ACM=n
CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_USBD_AUDIO2_CLASS=y
CONFIG_USBD_CDC_ACM_CLASS=n
CONFIG_USBD_LOG_LEVEL_WRN=y
CONFIG_USBD_UAC2_LOG_LEVEL_DBG=y
