#ifndef PLAY_DSP_DEFS_H
#define PLAY_DSP_DEFS_H

#define ANALYZER_WINDOW 512
#define ANALYZER_BINS 48
#define MAX_CHANNELS 2
#define EQ_BANDS 16
#define EQ_MIN_GAIN_DB -36.0f
#define EQ_MAX_GAIN_DB 36.0f
#define EQ_MIN_Q 0.3f
#define EQ_MAX_Q 12.0f
#define EQ_LOW_SVF_MAX_HZ 1000.0f

#define EQ_LINEAR_MAX_HZ 220.0f
#define EQ_DYNAMIC_MAX_HZ 16000.0f
#define PLAY_LINEAR_FIR_MAX_TAPS 33
#define PLAY_LINEAR_FIR_DEFAULT_TAPS 25
#define DYNAMIC_EQ_MIN_ATTACK 0.01f
#define DYNAMIC_EQ_MAX_ATTACK 0.50f
#define DYNAMIC_EQ_MIN_RELEASE 0.005f
#define DYNAMIC_EQ_MAX_RELEASE 0.30f
#define DYNAMIC_EQ_MIN_THRESHOLD 0.01f
#define DYNAMIC_EQ_MAX_THRESHOLD 1.00f
#define DYNAMIC_EQ_MIN_MAX_REDUCTION_DB 0.0f
#define DYNAMIC_EQ_MAX_MAX_REDUCTION_DB 36.0f
#define DYNAMIC_EQ_MIN_STRENGTH_DB 1.0f
#define DYNAMIC_EQ_MAX_STRENGTH_DB 36.0f

#define PLAY_MB_DYN_BANDS 8
#define PLAY_MB_DYN_MIN_DB -6.0f
#define PLAY_MB_DYN_MAX_DB 6.0f
#define PLAY_MB_DYN_MIN_THRESHOLD 0.01f
#define PLAY_MB_DYN_MAX_THRESHOLD 1.00f
#define PLAY_MB_DYN_MIN_ATTACK 0.002f
#define PLAY_MB_DYN_MAX_ATTACK 0.20f
#define PLAY_MB_DYN_MIN_RELEASE 0.005f
#define PLAY_MB_DYN_MAX_RELEASE 0.50f
#define PLAY_MB_DYN_MIN_STRENGTH 0.1f
#define PLAY_MB_DYN_MAX_STRENGTH 8.0f
#define PLAY_MB_DYN_DEFAULT_THRESHOLD 0.16f
#define PLAY_MB_DYN_DEFAULT_ATTACK 0.02f
#define PLAY_MB_DYN_DEFAULT_RELEASE 0.06f
#define PLAY_MB_DYN_DEFAULT_STRENGTH 1.2f

#define PLAY_DSP_PLUGIN_PHASE_ANALYZER 0x01u
#define PLAY_LOW_CROSSFEED_CUTOFF_HZ 150.0f
#define PLAY_LOW_CROSSFEED_RATIO 0.40f

typedef enum
{
    PLAY_CROSSFEED_PRE_EQ = 0,
    PLAY_CROSSFEED_POST_EQ = 1
} play_crossfeed_position;

typedef enum
{
    PLAY_EQ_MODE_LINEAR = 0,
    PLAY_EQ_MODE_DYNAMIC = 1,
    PLAY_EQ_MODE_NORMAL = 2
} play_eq_mode;

#endif