#ifndef MINIAUDIO_TINYUSB_UAC2_DESCRIPTORS_H_
#define MINIAUDIO_TINYUSB_UAC2_DESCRIPTORS_H_

#define TINYUSB_UAC2_ENTITY_CLOCK 0x04
#define TINYUSB_UAC2_ENTITY_INPUT_TERMINAL 0x01
#define TINYUSB_UAC2_ENTITY_FEATURE_UNIT 0x02
#define TINYUSB_UAC2_ENTITY_OUTPUT_TERMINAL 0x03

#define TINYUSB_UAC2_STEREO_SPEAKER_DESC_LEN ( \
    TUD_AUDIO20_DESC_IAD_LEN + \
    TUD_AUDIO20_DESC_STD_AC_LEN + \
    TUD_AUDIO20_DESC_CS_AC_LEN + \
    TUD_AUDIO20_DESC_CLK_SRC_LEN + \
    TUD_AUDIO20_DESC_INPUT_TERM_LEN + \
    TUD_AUDIO20_DESC_OUTPUT_TERM_LEN + \
    TUD_AUDIO20_DESC_FEATURE_UNIT_LEN(2) + \
    TUD_AUDIO20_DESC_STD_AS_LEN + \
    TUD_AUDIO20_DESC_STD_AS_LEN + \
    TUD_AUDIO20_DESC_CS_AS_INT_LEN + \
    TUD_AUDIO20_DESC_TYPE_I_FORMAT_LEN + \
    TUD_AUDIO20_DESC_STD_AS_ISO_EP_LEN + \
    TUD_AUDIO20_DESC_CS_AS_ISO_EP_LEN + \
    TUD_AUDIO20_DESC_STD_AS_ISO_FB_EP_LEN)

#define TINYUSB_UAC2_STEREO_SPEAKER_DESCRIPTOR(_itfnum, _stridx, _bytes, _bits, _epout, _epoutsize, _epfb, _epfbsize) \
    TUD_AUDIO20_DESC_IAD(_itfnum, 0x02, 0x00), \
    TUD_AUDIO20_DESC_STD_AC(_itfnum, 0x00, _stridx), \
    TUD_AUDIO20_DESC_CS_AC(0x0200, AUDIO20_FUNC_DESKTOP_SPEAKER, \
                           TUD_AUDIO20_DESC_CLK_SRC_LEN + TUD_AUDIO20_DESC_INPUT_TERM_LEN + \
                           TUD_AUDIO20_DESC_OUTPUT_TERM_LEN + TUD_AUDIO20_DESC_FEATURE_UNIT_LEN(2), \
                           AUDIO20_CS_AS_INTERFACE_CTRL_LATENCY_POS), \
    TUD_AUDIO20_DESC_CLK_SRC(TINYUSB_UAC2_ENTITY_CLOCK, AUDIO20_CLOCK_SOURCE_ATT_INT_PRO_CLK, \
                             AUDIO20_CTRL_RW << AUDIO20_CLOCK_SOURCE_CTRL_CLK_FRQ_POS, 0x01, 0x00), \
    TUD_AUDIO20_DESC_INPUT_TERM(TINYUSB_UAC2_ENTITY_INPUT_TERMINAL, AUDIO_TERM_TYPE_USB_STREAMING, 0x00, \
                                TINYUSB_UAC2_ENTITY_CLOCK, 0x02, AUDIO20_CHANNEL_CONFIG_NON_PREDEFINED, \
                                0x00, 0, 0x00), \
    TUD_AUDIO20_DESC_OUTPUT_TERM(TINYUSB_UAC2_ENTITY_OUTPUT_TERMINAL, AUDIO_TERM_TYPE_OUT_DESKTOP_SPEAKER, \
                                 0x01, TINYUSB_UAC2_ENTITY_FEATURE_UNIT, TINYUSB_UAC2_ENTITY_CLOCK, 0x0000, 0x00), \
    TUD_AUDIO20_DESC_FEATURE_UNIT(TINYUSB_UAC2_ENTITY_FEATURE_UNIT, TINYUSB_UAC2_ENTITY_INPUT_TERMINAL, 0x00, \
                                  AUDIO20_CTRL_RW << AUDIO20_FEATURE_UNIT_CTRL_MUTE_POS | AUDIO20_CTRL_RW << AUDIO20_FEATURE_UNIT_CTRL_VOLUME_POS, \
                                  AUDIO20_CTRL_RW << AUDIO20_FEATURE_UNIT_CTRL_MUTE_POS | AUDIO20_CTRL_RW << AUDIO20_FEATURE_UNIT_CTRL_VOLUME_POS, \
                                  AUDIO20_CTRL_RW << AUDIO20_FEATURE_UNIT_CTRL_MUTE_POS | AUDIO20_CTRL_RW << AUDIO20_FEATURE_UNIT_CTRL_VOLUME_POS), \
    TUD_AUDIO20_DESC_STD_AS_INT((uint8_t)((_itfnum) + 1), 0x00, 0x00, 0x00), \
    TUD_AUDIO20_DESC_STD_AS_INT((uint8_t)((_itfnum) + 1), 0x01, 0x02, 0x00), \
    TUD_AUDIO20_DESC_CS_AS_INT(TINYUSB_UAC2_ENTITY_INPUT_TERMINAL, AUDIO20_CTRL_NONE, AUDIO20_FORMAT_TYPE_I, \
                               AUDIO20_DATA_FORMAT_TYPE_I_PCM, 0x02, AUDIO20_CHANNEL_CONFIG_NON_PREDEFINED, 0x00), \
    TUD_AUDIO20_DESC_TYPE_I_FORMAT(_bytes, _bits), \
    TUD_AUDIO20_DESC_STD_AS_ISO_EP(_epout, (uint8_t)(TUSB_XFER_ISOCHRONOUS | TUSB_ISO_EP_ATT_ASYNCHRONOUS | TUSB_ISO_EP_ATT_DATA), _epoutsize, 0x01), \
    TUD_AUDIO20_DESC_CS_AS_ISO_EP(AUDIO20_CS_AS_ISO_DATA_EP_ATT_NON_MAX_PACKETS_OK, AUDIO20_CTRL_NONE, \
                                  AUDIO20_CS_AS_ISO_DATA_EP_LOCK_DELAY_UNIT_MILLISEC, 0x0001), \
    TUD_AUDIO20_DESC_STD_AS_ISO_FB_EP(_epfb, _epfbsize, 0x01)

#endif